pub fn goodSample(sequence: usize) []const u8 {
    return switch (sequence) {
        1 => "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":1,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}",
        else => "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":0,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}",
    };
}

pub fn sampleMissingPolicyAbi() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":6,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithInvalidDigest() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":7,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"not-a-sha256\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn goodSampleWithPrivate() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":1,\"cmdline\":\"demo\",\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn goodSampleWithGit(git_sha: []const u8) []const u8 {
    _ = git_sha;
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":2,\"git_sha\":\"old\",\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithRejectedDispatches() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":3,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 3\"},\"events_hash\":\"reject33\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"3\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithDeadWorkload() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":4,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"dead44\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\",\"workload_alive\":false,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithLoss() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":5,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"loss55\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"sample_loss\":{\"lost_samples\":1,\"backpressure_dropped\":0},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn richSample() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":8,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"rich88\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"sample_loss\":{\"lost_samples\":0,\"backpressure_dropped\":0,\"ring_buffer_overruns\":0,\"reader_lag_events\":0},\"dsq_depth\":{\"global\":2,\"local\":1,\"shared\":0},\"queue_latency\":{\"p50_us\":40,\"p95_us\":120,\"p99_us\":250,\"max_us\":300},\"fairness\":{\"state\":\"ok\",\"starved_tasks\":0,\"max_wait_us\":0},\"task_counts\":{\"by_cgroup_digest\":{\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\":3},\"by_class\":{\"interactive\":1,\"batch\":2}},\"scheduler_counters\":{\"context_switches\":123,\"wakeups\":45,\"migrations\":6},\"sched_ext_observation\":{\"dump\":{\"status\":\"present\",\"value\":\"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb;bytes:128\"},\"tracepoints\":{\"sched_switch\":123,\"sched_wakeup\":45}},\"benchmark_histograms\":[{\"record_path\":\"fixtures/benchmark-output/cyclictest-recorded.json\",\"record_sha256\":\"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\",\"histogram_id\":\"latency_us\",\"record_only\":true}],\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithDigestQuoteInjection() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":9,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"inject99\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"sched_ext_observation\":{\"dump\":{\"status\":\"present\",\"value\":\"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;bytes:128\\\",\\\"host_mutation\\\":true,\\\"x\\\":\\\"\"},\"tracepoints\":{\"sched_switch\":1}},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn goodAbiV3PolicySample() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":10,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"abiv3good\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_cgroup_abi_v3\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\",\"btf_required\":true,\"abi_version\":3,\"abi_label\":\"zigsched-bpf-abi-v3\",\"cgroup_semantics\":{\"cpu.weight\":\"callback-observed\",\"cgroup.lifecycle\":\"observed\",\"cgroup.move\":\"observed\",\"cpuset.cpus\":\"observed-only\",\"cpuset.cpus.effective\":\"observed-only\",\"cpu.pressure\":\"observed-only\",\"cpu.max\":\"deferred\",\"uclamp\":\"deferred\",\"cgroup_set_idle\":\"refused\"},\"vm_only\":true,\"host_mutation\":false,\"production_claim\":false,\"release_eligible\":false},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithBadAbiV3CpuMax() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":11,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"abiv3badmax\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_cgroup_abi_v3\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\",\"btf_required\":true,\"abi_version\":3,\"abi_label\":\"zigsched-bpf-abi-v3\",\"cgroup_semantics\":{\"cpu.weight\":\"callback-observed\",\"cgroup.lifecycle\":\"observed\",\"cgroup.move\":\"observed\",\"cpuset.cpus\":\"observed-only\",\"cpuset.cpus.effective\":\"observed-only\",\"cpu.pressure\":\"observed-only\",\"cpu.max\":\"observed-only\",\"uclamp\":\"deferred\",\"cgroup_set_idle\":\"refused\"},\"vm_only\":true,\"host_mutation\":false,\"production_claim\":false,\"release_eligible\":false},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithAbiV3HostMutationClaim() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":12,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"abiv3hostclaim\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_cgroup_abi_v3\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\",\"btf_required\":true,\"abi_version\":3,\"abi_label\":\"zigsched-bpf-abi-v3\",\"cgroup_semantics\":{\"cpu.weight\":\"callback-observed\",\"cgroup.lifecycle\":\"observed\",\"cgroup.move\":\"observed\",\"cpuset.cpus\":\"observed-only\",\"cpuset.cpus.effective\":\"observed-only\",\"cpu.pressure\":\"observed-only\",\"cpu.max\":\"deferred\",\"uclamp\":\"deferred\",\"cgroup_set_idle\":\"refused\"},\"vm_only\":true,\"host_mutation\":true,\"production_claim\":false,\"release_eligible\":false},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}
