pub fn goodSample(sequence: usize) []const u8 {
    return switch (sequence) {
        1 => "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":1,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}",
        else => "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":0,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}",
    };
}

pub fn sampleMissingPolicyAbi() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":6,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithInvalidDigest() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":7,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"not-a-sha256\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn goodSampleWithPrivate() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":1,\"cmdline\":\"demo\",\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn goodSampleWithGit(git_sha: []const u8) []const u8 {
    _ = git_sha;
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":2,\"git_sha\":\"old\",\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"ab12\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithRejectedDispatches() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":3,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 3\"},\"events_hash\":\"reject33\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"3\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithDeadWorkload() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":4,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"dead44\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\",\"workload_alive\":false,\"private_command_lines_sampled\":false}";
}

pub fn sampleWithLoss() []const u8 {
    return "{\"schema\":\"zig-scheduler/runtime-sample/v1\",\"sequence\":5,\"state\":{\"status\":\"present\",\"value\":\"enabled\"},\"ops\":{\"status\":\"present\",\"value\":\"zigsched_minimal\"},\"enable_seq\":{\"status\":\"present\",\"value\":\"42\"},\"events\":{\"status\":\"present\",\"value\":\"nr_rejected: 0\"},\"events_hash\":\"loss55\",\"nr_rejected\":{\"status\":\"present\",\"value\":\"0\"},\"debug_dump\":{\"status\":\"missing\",\"value\":\"\"},\"sample_loss\":{\"lost_samples\":1,\"backpressure_dropped\":0},\"policy_abi\":{\"policy_name\":\"zigsched_minimal\",\"policy_version\":\"sched_ext_minimal_v1\",\"struct_ops\":\"zigsched_minimal_ops\",\"object_sha256\":\"unavailable\",\"btf_required\":true},\"cgroup_membership_digest\":\"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\",\"workload_alive\":true,\"private_command_lines_sampled\":false}";
}
