from __future__ import annotations

from typing import Final

ROOT_FIELDS: Final[frozenset[str]] = frozenset({
    "schema",
    "sequence",
    "git_sha",
    "sample_source_event",
    "observation_source",
    "sched_ext_phase",
    "state",
    "ops",
    "enable_seq",
    "events",
    "events_hash",
    "nr_rejected",
    "debug_dump",
    "root_ops",
    "scheduler_events",
    "policy_counters",
    "sample_loss",
    "policy_abi",
    "cgroup_semantic_labels",
    "cgroup_membership_digest",
    "cgroup_membership_status",
    "task_ext_enabled",
    "teardown_state",
    "rollback_state",
    "workload",
    "workload_alive",
    "private_command_lines_sampled",
    "dsq_depth",
    "queue_latency",
    "fairness",
    "task_counts",
    "scheduler_counters",
    "sched_ext_observation",
    "benchmark_histograms",
})
